-- begin PURCHASE_CARD
create unique index IDX_PURCHASE_CARD_UNIQ_CARD_ID on PURCHASE_CARD (CARD_ID) ^
-- end PURCHASE_CARD
-- begin PURCHASE_ORDER
alter table PURCHASE_ORDER add constraint FK_PURCHASE_ORDER_ON_CLIENT foreign key (CLIENT_ID) references PURCHASE_CLIENT(ID)^
create unique index IDX_PURCHASE_ORDER_UNIQ_ORDER_ID on PURCHASE_ORDER (ORDER_ID) ^
create index IDX_PURCHASE_ORDER_ON_CLIENT on PURCHASE_ORDER (CLIENT_ID)^
-- end PURCHASE_ORDER
-- begin PURCHASE_CLIENT
alter table PURCHASE_CLIENT add constraint FK_PURCHASE_CLIENT_ON_CARD_ID foreign key (CARD_ID_ID) references PURCHASE_CARD(ID)^
create unique index IDX_PURCHASE_CLIENT_UNIQ_CLIENT_ID on PURCHASE_CLIENT (CLIENT_ID) ^
create index IDX_PURCHASE_CLIENT_ON_CARD_ID on PURCHASE_CLIENT (CARD_ID_ID)^
-- end PURCHASE_CLIENT
